server:
  port: ${APP_SERVER_PORT}
spring:
  jackson:
    mapper:
      default-view-inclusion: true
    serialization:
      indent-output: false
  session:
    store-type: none


qup:
  service:
    datasource:
      primary:
        url: ${APP_DB_NAME}
        driverClassName: ${APP_DB_DRIVER_CLASS}
        username: ${APP_DB_USERNAME}
        password: ${APP_DB_PASSWORD}
        max:
          connection:
            pool-size: ${APP_DB_MAX_CONNECTION_POOL_SIZE}
    jpa:
      packages-to-scan: com.jworks
      hibernate:
        show-sql: ${APP_DB_SHOW_SQL}
        ddl-auto: ${APP_DB_DDL_AUTO}
        dialect: ${APP_DB_DIALECT:org.hibernate.dialect.MySQL55Dialect}
    liquibase:
      enable: ${APP_LIQUIBASE_ENABLED}
      changelog: classpath:config/liquibase/index.xml
    jwt:
      secret: ${APP_JWT_SECRET}
      expiration-period-milli-seconds: ${APP_JWT_EXPIRATION_PERIOD_SECONDS}
    email:
      sender:
        name: ${EMAIL_SENDER_NAME}
        email-address: ${EMAIL_SENDER_ADDRESS}


sendgrid:
  api-key: ${SENDGRID_API_KEY}
  base-url: ${SEND_GRID_API_URL}
  user-notification-template-code: ${SEND_GRID_USER_NOTIFICATION_TEMPLATE_CODE}
  default-sender-address: ${SEND_GRID_USER_DEFAULT_ADDRESS}